### ISSUE TITLE
Modify the optin to not leave the screen unless all the mandatory fields are filled up

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog#150]
An opt-in form appears in the blog when a person visits it for the first time. It is controlled by a cookie `pop_up_sciblog`, if there is no cookie, the opt-in is shown, and if the cookie is there, the opt-in form is not shown. 
See opt-in below:
<img src="https://user-images.githubusercontent.com/3491412/199964453-4a9b63e4-eaf6-40e2-86a8-e655a721623b.png" alt="drawing" width="300"/>

The problem is that unless users filled up all the mandatory fields, the form doesn't work correctly. In particular, if a mandatory field is not filled up, the form sends you to an error page saying that a mandatory field was not added. When you go back to the home page, the cookie `pop_up_sciblog` is already created, so the opt-in won't appear again.

To solve the problem, I need to create a JS to show an error to users if they have not filled up the mandatory fields: First Name, Last Name, Email, and Marketing permission. I want the error to appear below each of the boxes in light red. 

The form can be found [here](https://github.com/miguelgfierro/sciblog/blob/main/blog/templates/desktop/blog/post_base.html):
```
<form action="https://miguelgfierro.com/sendy/subscribe" method="POST" accept-charset="utf-8"
          class="c-form c-form--accent c-subscribe-box__form">
          <input type="text" name="FirstName" id="FirstName" class="u-align-center pop-up-input"
            placeholder="First Name" />
          <input type="text" name="LastName" id="LastName" class="u-align-center pop-up-input"
            placeholder="Last Name" />
          <input type="email" name="email" id="email" class="u-align-center pop-up-input" placeholder="Email" />
          <input type="text" name="Linkedin" id="Linkedin" class="u-align-center pop-up-input" placeholder="LinkedIn" />
          <input type="checkbox" name="gdpr" id="gdpr" />
          <span class="c-subscribe-box__desc"><strong>Marketing permission</strong>:
            I give my consent to Miguel Fierro to be in touch with me via email for the purpose of news, updates and
            marketing.
          </span>
          <br /><br />
          <div style="display:none;">
            <label for="hp">HP</label><br />
            <input type="text" name="hp" id="hp" />
          </div>
          <input type="hidden" name="list" value="4XSoMExXeByg763RkCORqN7g" />
          <input type="hidden" name="subform" value="yes" />
          <input type="submit" name="submit" id="submit" class="full-button" placeholder="Send it to Me Now" />
        </form>
```

**Comment by Backendeng** [comment]
Hi, 
this issues can resolve in JavaScript.
Can we chat on telegram ?

**Comment by vishal-singh-810** [comment]
Hi, let's chat on WhatsApp.

+91-9569990556.
