### ISSUE TITLE
Update to python >3.5

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog#29]
This blog was initially created with python 2.7, I haven't had time to upgraded. Any collaboration is welcommed :-)

**Comment by ankur09011** [comment]
Hey, I can help here, any particular idea in mind

**Comment by miguelgfierro** [comment]
@ankur09011 that would be awesome!

Right now the blog uses django 1.7 and python 2.7. Do you think it would be easy to have full compatiility with python >3.5 and a newer version of django?

**Comment by ankur09011** [comment]
@miguelgfierro Yes I think, also it would be better to move it to 3.x

**Comment by ankur09011** [comment]
@miguelgfierro let me know your plans about this, I will then create a roadmap for the same

**Comment by miguelgfierro** [comment]
Here a proposal:

- [ ]  Migrate [sciblog folder](./sciblog) to django 2 and python 3.x
- [ ] Check that the front end html works as expected (modify if not)
- [ ] Check that the js to generate pages of two columns works as expected (modify if not)
- [ ] Check that ckeditor works as expected (modify if not)
- [ ] Make sure everything works as expected in production and create a PR to master
- [ ] Upgrade to sciblog release 3.0

**Comment by ankur09011** [comment]
@miguelgfierro ok thanks, I will be doing point 1 "Migrate sciblog folder to django 2 and python 3.x" first

**Comment by miguelgfierro** [comment]
Awesome. Tell me whats your preference, I can create a new branch called python3_dev in case you want to merge there or you prefer to work on your own repo?

**Comment by ankur09011** [comment]
@miguelgfierro new branch called "python3_dev" works fine.

**Comment by miguelgfierro** [comment]
Note: according to this web: https://docs.djangoproject.com/en/1.8/releases/1.8/, Django 1.8 requires Python 2.7, 3.2, 3.3, 3.4, or 3.5. So I could start just changing the python version to 3.5, and then in a second iteration, upgrading Django.

**Comment by miguelgfierro** [comment]
- [ ] Migrate the code to python3
- [ ] Make sure that a working dataset can be used in the same system
- [ ] Update the apache installation
- [ ] Make sure that the blog runs in a host
